//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TeleopInterfaces
{
    [Serializable]
    public class GraspTriggerRequest : Message
    {
        public const string k_RosMessageName = "teleop_interfaces/GraspTrigger";
        public override string RosMessageName => k_RosMessageName;

        //  Custom service to request grasp poses from a given point cloud
        public Std.Float64MultiArrayMsg gaze_point;

        public GraspTriggerRequest()
        {
            this.gaze_point = new Std.Float64MultiArrayMsg();
        }

        public GraspTriggerRequest(Std.Float64MultiArrayMsg gaze_point)
        {
            this.gaze_point = gaze_point;
        }

        public static GraspTriggerRequest Deserialize(MessageDeserializer deserializer) => new GraspTriggerRequest(deserializer);

        private GraspTriggerRequest(MessageDeserializer deserializer)
        {
            this.gaze_point = Std.Float64MultiArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gaze_point);
        }

        public override string ToString()
        {
            return "GraspTriggerRequest: " +
            "\ngaze_point: " + gaze_point.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
