//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TeleopInterfaces
{
    [Serializable]
    public class ManipulatorWaypointsResponse : Message
    {
        public const string k_RosMessageName = "teleop_interfaces/ManipulatorWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public bool recieved;

        public ManipulatorWaypointsResponse()
        {
            this.recieved = false;
        }

        public ManipulatorWaypointsResponse(bool recieved)
        {
            this.recieved = recieved;
        }

        public static ManipulatorWaypointsResponse Deserialize(MessageDeserializer deserializer) => new ManipulatorWaypointsResponse(deserializer);

        private ManipulatorWaypointsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.recieved);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.recieved);
        }

        public override string ToString()
        {
            return "ManipulatorWaypointsResponse: " +
            "\nrecieved: " + recieved.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
