//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TeleopInterfaces
{
    [Serializable]
    public class SendTransformRequest : Message
    {
        public const string k_RosMessageName = "teleop_interfaces/SendTransform";
        public override string RosMessageName => k_RosMessageName;


        public SendTransformRequest()
        {
        }
        public static SendTransformRequest Deserialize(MessageDeserializer deserializer) => new SendTransformRequest(deserializer);

        private SendTransformRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SendTransformRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
