//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TeleopInterfaces
{
    [Serializable]
    public class SendTransformResponse : Message
    {
        public const string k_RosMessageName = "teleop_interfaces/SendTransform";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TransformStampedMsg transform;

        public SendTransformResponse()
        {
            this.transform = new Geometry.TransformStampedMsg();
        }

        public SendTransformResponse(Geometry.TransformStampedMsg transform)
        {
            this.transform = transform;
        }

        public static SendTransformResponse Deserialize(MessageDeserializer deserializer) => new SendTransformResponse(deserializer);

        private SendTransformResponse(MessageDeserializer deserializer)
        {
            this.transform = Geometry.TransformStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.transform);
        }

        public override string ToString()
        {
            return "SendTransformResponse: " +
            "\ntransform: " + transform.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
